[input]
target_folder = "/home/mark/Repositories/Python/Neuron/new_data"
method = "previous"
SD_multiplier = 3
smoothing_range = 5
amp_threshold = 0.3
cv_threshold = 0.1
correction = "False"

[output]
report_name = "report_"
summary_name = "summary"
