name: Build Linux releases

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install tk package
              shell: bash
              run: |
                sudo apt update
                sudo apt install python3-tk -y

            - name: Install my project
              run: uv sync --locked --all-extras --dev

            - name: AOT compile smoothing function
              run: |
                cd src/neuron/analysis/compiled
                uv run compile_smooth.py build_ext --inplace
                cd ../../../..
              # looks dumb, but there is a reason for it: having a setup.py at the project root would imply it's
              # meant to package the whole project, but here I only use it for this one file

            - name: Compile project with Nuitka
              run: uv run nuitka --standalone src/neuron/main.py -o Neuron --enable-plugins=tk-inter

            - name: Upload compiled program
              uses: actions/upload-artifact@v6
              with:
                name: Neuron-${{ runner.os }}
                path: Neuron.dist
