name: Build releases

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install my project
              run: uv sync --locked --all-extras --dev

            - name: AOT compile smoothing function
              run: cd src/neuron/compiled && uv run compile_smooth.py build_ext --inplace && cd ../../..
              # looks dumb, but there is a reason for it: having a setup.py at the project root would imply it's
              # meant to package the whole project, but here I only use it for this one file

            - name: Rename compiled extension
              shell: bash
              run: |
                TARGET_DIR="src/neuron/compiled"
                
                if [ "${{ runner.os }}" == "Windows" ]; then
                  mv $TARGET_DIR/cy_smooth.cpython*.pyd $TARGET_DIR/cy_smooth.pyd
                else
                  mv $TARGET_DIR/cy_smooth.cpython*.so $TARGET_DIR/cy_smooth.so
                fi

            - name: Compile project with Nuitka
              run: uv run nuitka --standalone main.py --enable-plugins=tk-inter
