name: Build Linux release

on:
    workflow_dispatch

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Install uv
              uses: astral-sh/setup-uv@v7

            - name: Install tk package
              shell: bash
              run: |
                sudo apt update
                sudo apt install python3-tk -y

            - name: Install my project
              run: uv sync --locked --all-extras

            - name: AOT compile smoothing function
              run: |
                cd src/analysis/compiled
                uv run compile_smooth.py build_ext --inplace
                cd ../../../..
              # looks dumb, but there is a reason for it: having a setup.py at the project root would imply it's
              # meant to package the whole project, but here I only use it for this one file

            - name: Compile project with Nuitka
              shell: bash
              run: |
                uv run python -m nuitka \
                --standalone \
                src/main.py \
                --enable-plugins=tk-inter \
                --assume-yes-for-downloads \
                --include-package=pandas \
                --output-filename=Analyzer

            - name: Copy the License and README
              shell: bash
              run: |
                cp LICENSE main.dist/LICENSE.txt
                cp README.md main.dist/README.md

            - name: Upload compiled program
              uses: actions/upload-artifact@v6
              with:
                name: Neuron-${{ runner.os }}
                path: main.dist
